### ISSUE TITLE
[Bug] Language and region  list is empty

### ISSUE THREAD

**Issue by odin3** [elementary/switchboard-plug-locale#24] opened 2017-05-23 21:37 UTC
## Environment
**OS**: Elementary OS 0.4.1
**Hardware**: 
```
VMWare Workstation 12 Pro
RAM: 2 GB
```

## Comment
Language and region dropdowns are empty at `locale` section
Screenshot: 
![image](https://cloud.githubusercontent.com/assets/9203548/26377462/120fa894-4019-11e7-8689-89fe5cc3cb9f.png)

## Steps to reproduce
1. Install a fresh copy on Elementary OS
2. Select `Russian` as primary UI language
3. Go to Settings -> Locale

**Comment by davidmhewitt** [comment] 2017-05-23 21:40
Thank you for taking the time to file all of these reports.

Marking this as a duplicate of #21 which was fixed yesterday. Just waiting for the update to be pushed.

**Closed by davidmhewitt** 2017-05-23 21:40 UTC
