### ISSUE TITLE
Setting region to South Africa is not persistent and doesn't adjust system clock

### ISSUE THREAD

**Issue by EidoJ** [elementary/switchboard-plug-locale#173] opened 2022-12-05 22:50 UTC
### What Happened?

On a fresh install of eOS 6 I could not get my system clock set to my region time (UTC + 2 - South Africa). Changing the Region setting to South Africa is not persistent. Logging out and in again does not fix it. Saving system language (sudo password) does not fix it either.

Issue discovered on bare metal computer.
Reproduced in VirtualBox: 
[elementary OS 6 test-screen0.webm](https://user-images.githubusercontent.com/3705829/205757571-0a6fce18-12a5-456d-afc8-1680f4ce69fe.webm)

Logs from bare metal machine: 
[region setting bug report console output.log](https://github.com/elementary/switchboard-plug-locale/files/10158463/region.setting.bug.report.console.output.log)

### Steps to Reproduce

1. Install a fresh copy of eOS 6 with South African locale and keyboard (US layout); English United Kingdom language.
2. In the first boot wizard, choose the same above settings. You will need to click around and set the layout to something else and back before you can continue on the keyboard layout page.
3. Log in and observe that time is synchronised to UTC, not UTC + 2.
4. Open Settings -> Language & Region and change to South Africa (it is probably set to United Kingdom). Close switchboard, then re-open Settings -> Language & Region. Notice Region is probably set to United States.
5. If you'd like, set it again to South Africa, log out and back in again or reboot, noticing that it doesn't fix the issue.

### Expected Behavior

Clock should be synchronised to South African time.
Region should persist.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Virtualbox:
- RAM: 6GB
- Cores: 6
- Display: 128MB VMSVGA

Bare metal PC:
- RAM: 16GB DDR4
- CPU: AMD Ryzen 5 1600
- GPU: AMD Radeon RX580

**Comment by danirabbit** [comment] 2024-03-09 18:39
Hey thanks for your report. In the future please make sure to file separate reports for each issue you experience. It's not possible for us to track grouped issue reports.

It looks like part of this is a duplicate of #183 

The other part seems to be just a misunderstanding. The "Region" setting is for choosing the regional dialect of your language. It doesn't effect Date & Time settings. I've proposed #202 to make it more clear that Date & Time settings is a separate section

**Comment by danirabbit** [comment] 2024-03-09 18:40
Closing as a duplicate and also because grouped reports are not trackable

**Closed by danirabbit** 2024-03-09 18:40 UTC
