### ISSUE TITLE
Cannot set up Finnish language as system default in Elementary OS

### ISSUE THREAD

**Issue by msaastam** [elementary/switchboard-plug-locale#85] opened 2019-05-28 09:47 UTC
Cannot set up Finnish language as system default in Elementary OS.  Some parts of OS is set as Finnish language, but "Set system language" doesn't work correctly. Some parts of OS are still in English.

Also "Set up default language" comes back every time when You logged in and ask to to same operation again.

That causes a problem when installing other applications in the selected language!

**Comment by peteruithoven** [comment] 2019-05-28 10:15
Please refrain from using !'s, that can come across as rude. 

> Cannot set up Finnish language as system default in Elementary OS.

Could you clarify? Could you show a screenshot of how this fails? I'm assuming you can but parts are still showing in English? If that's the case that's probably because they are not translated yet, which wouldn't be a valid issue for the locale settings.
More information on how you can contribute to translations: https://elementary.io/get-involved#translations

> Also "Set up default language" comes back every time when You logged in and ask to to same operation again.

This sounds like a separate issue, please open a separate issue. Preferably where you clarify this a bit more, maybe using a screenshot.

**Comment by msaastam** [comment] 2019-05-28 18:39
Hey Peter,

Sorry, English is not one of my strongest sides :)

Here are some screenshots which I will try to explain below:
System installed and Finnish is selected for language default. Don't have
right picture where after install OS says something that "Language support
is not fully installed" or something like that. You must login with
administrative rights to continue and install rest of language support.
Then You must to logoff and login again to get upgrades uptodate. When You
came back to Language settings and You see that OS ask You to do it again
(Screenshot_4.png). So it can't complete succesfully?

Screenshot_5 trying to tell situation where language settings are set up
right. Then when You going to install new software they should be showed by
default language. Now some of the applications are in Finnish and some in
English. Screencapture_6.png shows that some of the languages are
translated and some are not. When installing applications, should they not
be installed in the default language (at least Libre Office)? Now they are
installed in English. The Libreoffice Regulations do not have the
possibility to change the language in English. At least earlier on other
Linux systems I don't remember having to install any language pack
separately.

Hopefully you will now know what the probe was saying. And sorry if I was
somehow rude in my message. Otherwise, the system feels right!

BR,
\\Mika



ti 28. toukok. 2019 klo 13.15 Peter Uithoven (notifications@github.com)
kirjoitti:

**Comment by peteruithoven** [comment] 2019-05-28 19:56
@msaastam I'm afraid I don't see the screenshots. Maybe that doesn't work through email. 

Please open a seperate issue for the "Language support is not fully installed" issue.

**Comment by danirabbit** [comment] 2024-03-09 18:45
The half of this about incomplete language support seems to be a duplicate of #132 

The issue with LibreOffice is specific to installing the deb version which we don't support. Libreoffice installed via flatpak works as expected with regards to language support.

Closing since part of this is a duplicate and the other part is solved in the last 5 years by switching to Flatpak :)

**Closed by danirabbit** 2024-03-09 18:45 UTC
Labels: i18n
